---

Tools: /home/{{ ansible_user }}/Tools/
Tools_Windows: /home/{{ ansible_user }}/Tools/Windows
Tools_Linux: /home/{{ ansible_user }}/Tools/Linux
Tools_Generic: /home/{{ ansible_user }}/Tools/Generic

Lists: /home/{{ ansible_user }}/Lists/

Terminal_Settings: /etc/xdg/qterminal.org/qterminal.ini

InitialPackages:
- remmina
- ltrace
- strace
- hexedit
- php-cli
- gobuster
- havoc
- snmp-mibs-downloader
- apt-transport-https # Docker Start
- ca-certificates
- curl
- software-properties-common
- python3-pip
- virtualenv
- python3-setuptools # Docker End
- mono-devel
- pipx
- ligolo-ng
- netexec


PipInstalls:
 - pyftpdlib
 - pyasn1
 - dulwich
 - updog
 - uploadserver
 - grip
 - smbclientng
 - bopscrk

#PipxInstalls:
# - git+https://github.com/Pennyw0rth/NetExec

DockerImages:
 - postgres:13.2
 - neo4j:4.4
 - woahbase/alpine-python2
 - specterops/bloodhound


ListsGit:
- https://github.com/danielmiessler/SecLists
- https://github.com/insidetrust/statistically-likely-usernames
- https://github.com/ignis-sec/Pwdb-Public

############# Gits
LinuxToolsGit:
- https://github.com/arthaud/git-dumper
- https://github.com/internetwache/GitTools
- https://github.com/nsonaniya2010/SubDomainizer

WindowsToolsGit:
  #- https://github.com/login-securite/DonPAPI
- https://github.com/PowerShellMafia/PowerSploit
- https://github.com/Kevin-Robertson/Powermad
- https://github.com/S3cur3Th1sSh1t/PowerSharpPack
- https://github.com/r3motecontrol/Ghostpack-CompiledBinaries
- https://github.com/ParrotSec/mimikatz
- https://github.com/dirkjanm/CVE-2020-1472
- https://github.com/itm4n/PrivescCheck

GenericToolsGit:
- https://github.com/arthaud/git-dumper

ListsGit:
- https://github.com/danielmiessler/SecLists
- https://github.com/insidetrust/statistically-likely-usernames


############# Downloads
LinuxToolsDownloads:
- https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
- https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy32
- https://github.com/DominicBreuker/pspy/releases/download/v1.2.1/pspy64

WindowsToolsDownloads:
- https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
- https://raw.githubusercontent.com/SpecterOps/bloodhound/main/examples/docker-compose/docker-compose.yml
- https://download.sysinternals.com/files/SysinternalsSuite.zip
- https://raw.githubusercontent.com/samratashok/nishang/master/Shells/Invoke-PowerShellTcp.ps1
- https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe
- https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe

ListDownloads:
- 


############# Compressed
WindowsToolsCompressed:
- https://download.sysinternals.com/files/SysinternalsSuite.zip
