---

Tools: /home/{{ ansible_user }}/Tools/
Tools_Windows: /home/{{ ansible_user }}/Tools/Windows
Tools_Linux: /home/{{ ansible_user }}/Tools/Linux
Tools_Generic: /home/{{ ansible_user }}/Tools/Generic

Havoc_Dir: /home/{{ ansible_user }}/Havoc

Terminal_Settings: /etc/xdg/qterminal.org/qterminal.ini

InitialPackages:
- bloodhound
- neo4j
- crackmapexec
- remmina
- ltrace
- strace
- hexedit
- php-cli
- gobuster
- git # Havoc start
- build-essential 
- apt-utils
- cmake 
- libfontconfig1
- libglu1-mesa-dev
- libgtest-dev
- libspdlog-dev
- libboost-all-dev
- libncurses5-dev
- libgdbm-dev
- libssl-dev
- libreadline-dev
- libffi-dev
- libsqlite3-dev
- libbz2-dev
- mesa-common-dev
- qtbase5-dev
- qtchooser
- qt5-qmake
- qtbase5-dev-tools
- libqt5websockets5
- libqt5websockets5-dev
- qtdeclarative5-dev
- golang-go
- qtbase5-dev
- libqt5websockets5-dev
- python3-dev
- libboost-all-dev
- mingw-w64
- nasm # Havoc end
- snmp-mibs-downloader
- apt-transport-https # Docker Start
- ca-certificates
- curl
- software-properties-common
- python3-pip
- virtualenv
- python3-setuptools # Docker End
- mono-devel


PipInstalls:
 - pyftpdlib
 - pyasn1
 - dulwich
 - updog
 - uploadserver
 - grip


WindowsToolsGit:
  #- https://github.com/login-securite/DonPAPI
- https://github.com/BloodHoundAD/BloodHound
- https://github.com/PowerShellMafia/PowerSploit
- https://github.com/Kevin-Robertson/Powermad
- https://github.com/S3cur3Th1sSh1t/PowerSharpPack
- https://github.com/r3motecontrol/Ghostpack-CompiledBinaries
- https://github.com/ParrotSec/mimikatz
- https://github.com/dirkjanm/CVE-2020-1472
- https://github.com/itm4n/PrivescCheck

LinuxToolsGit:
- https://github.com/arthaud/git-dumper
- https://github.com/internetwache/GitTools
- https://github.com/nsonaniya2010/SubDomainizer
