---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Add ansible_user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true