############## Check for path, if no path -> clone
- name: Checking for {{ item.split('/') | last }}
  stat: 
    path: "{{ dir }}/{{ item.split('/') | last }}"
  register: git_path

- name: Cloning {{ item.split('/') | last }}
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ dir }}/{{ item.split('/') | last }}"
  when: git_path.stat.exists == false
