---
- name: Cloning Havoc C2
  git:
    repo: https://github.com/HavocFramework/Havoc.git
    dest: "{{ Havoc_Dir }}"
    update: yes

- name: Installing Havoc C2 Go dependancies
  shell: |
    go mod download golang.org/x/sys && go mod download github.com/ugorji/go
  args:
    chdir: "{{ Havoc_Dir }}/teamserver"

- name: Making Havoc C2 TeamServer
  shell: |
    make ts-build
  args:
    chdir: "{{ Havoc_Dir }}"

- name: Making Havoc C2 Client
  shell: |
    make client-build
  args:
    chdir: "{{ Havoc_Dir }}"
