# Installations
- include_tasks: checks.yml
- include_tasks: installs.yml

- include_tasks: sliver.yml
  when: not sliver_exists

# Fix terminal
- include_tasks: terminal.yml

# Wallpaper
- include_tasks: wallpaper.yml

# Folders
- include_tasks: folders.yml

# Tooling
############# Gits
- include_tasks: tooling_git.yml
  vars:
      os: "Windows"
  loop: "{{ WindowsToolsGit }}"

- include_tasks: tooling_git.yml
  vars:
      os: "Linux"
  loop: "{{ LinuxToolsGit }}"

############# Downloads
- include_tasks: tooling_download.yml
  vars:
      os: "Windows"
  loop: "{{ WindowsToolsDownloads }}"

- include_tasks: tooling_download.yml
  vars:
      os: "Linux"
  loop: "{{ LinuxToolsDownloads }}"

############# Compressed
- include_tasks: tooling_compressed.yml
  vars:
      os: "Windows"
  loop: "{{ WindowsToolsCompressed }}"

- include_tasks: docker.yml
- include_tasks: docker_images.yml
  loop: "{{ DockerImages }}"

- include_tasks: snmp.yml
- include_tasks: fix_metasploit.yml

- include_tasks: cleanup.yml