############## Kerbrute
- name: Downloading Kerbrute
  ansible.builtin.get_url:
    url: https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
    dest: "{{ Tools_Windows }}/kerbrute"
    mode: a+x

############## SysInternals
- name: Create a Sysinternals directory
  ansible.builtin.file:
    path: "{{ Tools_Windows }}/SysInternals"
    state: directory
    mode: '0755'

- name: Download Sysinternals
  ansible.builtin.unarchive:
    src: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: "{{ Tools_Windows }}/SysInternals"
    remote_src: yes

############## Random scripts etc
- name: Download Invoke-PowerShellTcp.ps1
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/samratashok/nishang/master/Shells/Invoke-PowerShellTcp.ps1
    dest: "{{ Tools_Windows }}/Invoke-PowerShellTcp.ps1"

- name: Download PrintSpoofer32.exe
  ansible.builtin.get_url:
    url: https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe
    dest: "{{ Tools_Windows }}/PrintSpoofer32.exe"

- name: Download PrintSpoofer64.exe
  ansible.builtin.get_url:
    url: https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe
    dest: "{{ Tools_Windows }}/PrintSpoofer64.exe"

    
    