############## Kerbrute
- name: Downloading Kerbrute
  ansible.builtin.get_url:
    url: https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
    dest: "{{ Tools_Windows }}/kerbrute"
    mode: a+x

############## SysInternals
- name: Create a Sysinternals directory
  ansible.builtin.file:
    path: "{{ Tools_Windows }}/SysInternals"
    state: directory
    mode: '0755'

- name: Download Sysinternals
  ansible.builtin.unarchive:
    src: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: "{{ Tools_Windows }}/SysInternals"
    remote_src: yes