---
############## LinPeas
- name: Downloading LinPeas
  ansible.builtin.get_url:
    url: https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh
    dest: "{{ Tools_Linux }}/linpeas.sh"

- name: Downloading pspy64
  ansible.builtin.get_url:
    url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
    dest: "{{ Tools_Linux }}/pspy64"

- name: Downloading pspy32
  ansible.builtin.get_url:
    url: https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy32
    dest: "{{ Tools_Linux }}/pspy32"