---
- name: Copy wallpaper to host
  ansible.builtin.copy:
    src: wallpaper.jpg
    dest: /home/{{ ansible_user }}/Pictures/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'